Repository The-Standard-Organization/ADotNet, pull requests merged in 2025-01, with the labels that each got.

#127 MINOR FOUNDATIONS: CheckoutTaskV4
  ADotNet/Models/Pipelines/GithubPipelines/DotNets/Tasks/CheckoutTaskV4.cs
Labels: FOUNDATIONS

#128 FOUNDATIONS: Require Issue Or Task
  .github/workflows/build.yml
  .github/workflows/prLinter.yml
  ADotNet.Infrastructure.Build/ADotNet.Infrastructure.Build.csproj
  ADotNet.Infrastructure.Build/Program.cs
  ADotNet.Infrastructure.Build/Services/ScriptGenerationService.cs
  ADotNet/Models/Pipelines/GithubPipelines/DotNets/RequireIssueOrTaskJob.cs
  AdoNet.Tests.Console/ADotNet.Tests.Console.csproj
  AdoNet.Tests.Unit/ADotNet.Tests.Unit.csproj
Labels: FOUNDATIONS

#124 DOCUMENTATION: Readme Build Badge Fix
  README.md
Labels: DOCUMENTATION

#133 RELEASES: v4.0.0
  ADotNet/ADotNet.csproj
Labels: RELEASES

#147 EXPOSERS: Fluent GitHub Pipeline Builder
  ADotNet/ADotNet.csproj
  ADotNet/Clients/ADotNetClient.cs
  ADotNet/Clients/Builders/GitHubPipelineBuilder.cs
  ADotNet/Clients/Builders/JobBuilder.cs
  AdoNet.Tests.Console/Program.cs
  AdoNet.Tests.Unit/Clients/Builders/GitHubPipelineBuilderTests.Logic.cs
  AdoNet.Tests.Unit/Clients/Builders/GitHubPipelineBuilderTests.cs
Labels: EXPOSERS

#149 DOCUMENTATION: Fluent API
  README.md
Labels: DOCUMENTATION

#150 RELEASES: v4.1.0
  ADotNet/ADotNet.csproj
Labels: RELEASES
